#!/usr/bin/env bash

set -o errexit
set -o pipefail

usage() {
	echo "usage: setup <link|install>"
	echo ""
	echo "link - symlink configuraion files"
	echo "install - install system packages"
}

link() {
	mkdir -p "$XDG_CONFIG_HOME/emacs"
	mkdir -p "$XDG_CONFIG_HOME/rustfmt"

	ln -s "$PWD/shell/.bashrc" "$HOME/.bashrc"
	ln -s "$PWD/shell/.profile" "$HOME/.profile"
	ln -s "$PWD/shell/.inputrc" "$HOME/.inputrc"
	ln -s "$PWD/fonts/archives" "$XDG_DATA_HOME/fonts"
	ln -s "$PWD/emacs/init.el" "$XDG_CONFIG_HOME/emacs/init.el"
	ln -s "$PWD/emacs/themes" "$XDG_CONFIG_HOME/emacs/themes"
	ln -s "$PWD/rust/rustfmt.toml" "$XDG_CONFIG_HOME/rustfmt/rustfmt.toml"
	ln -s "$PWD/git" "$XDG_CONFIG_HOME/git"
}

install() {
	sudo apt install -y $(xargs <packages)
}

case "$1" in
	link) link;;
	install) install;;
	*) usage;;
esac
